security:
    # Password hashing configuration
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    # User provider: load users from the database
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        # Disable security for dev assets
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall
        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login     # route name for login
                check_path: app_login     # route name to submit credentials
                username_parameter: email  # nom du champ « identifiant »
                password_parameter: password# nom du champ « mot de passe »
                enable_csrf: true         # active la protection CSRF
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate

            logout:
                path: app_logout         # route name for logout
                invalidate_session: true
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true

    access_control:
        # Order matters: first match is used
        - { path: ^/admin,   roles: ROLE_ADMIN }
        - { path: ^/employe, roles: ROLE_EMPLOYEE }
        - { path: ^/profil,  roles: ROLE_USER }
